### ISSUE TITLE
cd /data/installk8s/sysbase && ./bin/sysbase-amd64 执行失败

### ISSUE THREAD

**Issue by flyflypeng** [yonyoucloud/install_k8s#37]
参考[安装说明](https://github.com/yonyoucloud/install_k8s/blob/master/images/install_readme.pdf)文档中的方法，下载下来了离线包，然后解压后执行到`cd /data/installk8s/sysbase && ./bin/sysbase-amd64`时就失败了：
```bash
root@flyflypeng-desktop-k8s-worker:/data# cd /data/installk8s/sysbase && ./bin/sysbase-amd64
2021/07/07 23:01:39 
sysbase

2021/07/07 23:01:39 /ext-go/1/src/esn/sysbase/backend/model/model.go:31
[error] failed to initialize database, got error dial tcp 127.0.0.1:5001: connect: connection refused

2021/07/07 23:01:39 /go/pkg/mod/gorm.io/plugin/dbresolver@v1.1.0/dbresolver.go:131
[error] failed to initialize database, got error dial tcp 127.0.0.1:5001: connect: connection refused
2021/07/07 23:01:39 dial tcp 127.0.0.1:5001: connect: connection refused
panic: dial tcp 127.0.0.1:5001: connect: connection refused


goroutine 1 [running]:
log.Panicln(0xc0002c1d30, 0x1, 0x1)
        /usr/local/go/src/log/log.go:352 +0xac
git.yonyou.com/sysbase/backend/model.InitDB(0xc00006e070, 0x67, 0xc000020420, 0x1, 0x1, 0xc00000ed60, 0x2, 0x2, 0x0, 0x0, ...)
        /ext-go/1/src/esn/sysbase/backend/model/model.go:59 +0x5e2
git.yonyou.com/sysbase/backend/server.(*Server).Run(0xc0002c1f38, 0xc34d14, 0xf)
        /ext-go/1/src/esn/sysbase/backend/server/unix.go:33 +0x98
main.main()
        /ext-go/1/src/esn/sysbase/backend/main.go:64 +0x143
```

**Comment by flyflypeng** [comment]
好的，感谢！
